apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  labels:
    app: my-app
type: Opaque
data:
  DB_USERNAME: dXNlcm5hbWU==
  DB_PASSWORD: cGFzc3dvcmQ==
# echo -n "username" | base64

# kubectl create secret generic my-app-secret \
# --from-literal=DB_USERNAME=username \
# --from-literal=DB_PASSWORD=password
