apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000
  type: NodePort
