apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
  labels:
    app: simulador-do-caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
        - name: simulador-do-caos
          image: registry.k8s.io/busybox
          command:
            - /bin/sh
          args:
            - -c
            - touch /tmp/ready; sleep 30; rm -f /tmp/ready; sleep 600;
          ports:
            - containerPort: 3000
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/ready
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
            successThreshold: 2
            timeoutSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
  labels:
    app: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
