apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
  labels:
    app: simulador-do-caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
        - name: simulador-do-caos
          image: kubedevio/simulador-do-caos:v1
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /health
              port: 3000
              failureThreshold: 30
              periodSeconds: 5
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
  labels:
    app: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
