apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
  labels:
    app: simulador-do-caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
        - name: simulador-do-caos
          image: registry.k8s.io/goproxy:0.1
          ports:
            - containerPort: 8080
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
  labels:
    app: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
